<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <UserSecretsId>72f4f1bf-76d5-4020-a909-dfa86843dae4</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Appium.WebDriver" Version="4.3.0" />
		<PackageReference Include="xunit" Version="2.6.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.5.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
	</ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>